# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c4a82b26c3751fe95a416dce6ded52420e4105ac85a3851ea42babfeccb79f3989f4d18c1ee87c2f0874b50e9e75e0a1b842b706ab86f4085f1c7b28aec0717

test:
  secret_key_base: 1d3684e99f6ae1298ead93c3921e2368c034d3bdc56c236267d0ee8060f2e0350a10a0d15439c17e804ad48ddbfc0163d10b8ceb6af33681c3c2b9ead5995d1a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
